"""add_campos_acrescimo_e_desconto_na_tabela_vendas

Revision ID: 070e4e7a8db7
Revises: 07292680f497
Create Date: 2026-03-07 18:51:09.847410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070e4e7a8db7'
down_revision: Union[str, None] = '07292680f497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('desconto', sa.Float(), nullable=False, server_default='0'))
    op.add_column('vendas', sa.Column('acrescimo', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'acrescimo')
    op.drop_column('vendas', 'desconto')
    # ### end Alembic commands ###
