"""add campo ativo

Revision ID: 096388abff7b
Revises: 8afe9c620c25
Create Date: 2026-02-19 17:49:27.785232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096388abff7b'
down_revision: Union[str, None] = 'b080f043af0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


    
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('produtos', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('vendas', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendas', 'ativo')
    op.drop_column('produtos', 'ativo')
    op.drop_column('categorias', 'ativo')
    # ### end Alembic commands ###
