"""add_controle_de_turno

Revision ID: 26880ca9dd57
Revises: d9ec20bcaf49
Create Date: 2026-03-18 02:01:52.133914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26880ca9dd57'
down_revision: Union[str, None] = 'd9ec20bcaf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='turnostatus'), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valor_inicial', sa.Float(), nullable=False),
    sa.Column('valor_informado', sa.Float(), nullable=True),
    sa.Column('valor_esperado', sa.Float(), nullable=True),
    sa.Column('diferenca', sa.Float(), nullable=True),
    sa.Column('total_vendas', sa.Float(), nullable=False),
    sa.Column('quantidade_vendas', sa.Integer(), nullable=False),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    op.add_column('vendas', sa.Column('turno_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vendas', 'turnos', ['turno_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint('vendas_turno_id_fkey', 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'turno_id')
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_table('turnos')
    op.execute("DROP TYPE IF EXISTS turnostatus")
