"""add_estoque_minimo_produto

Revision ID: 7cf26d5a921b
Revises: 26880ca9dd57
Create Date: 2026-03-22 22:14:52.959227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf26d5a921b'
down_revision: Union[str, None] = '26880ca9dd57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('estoque_minimo', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'estoque_minimo')
    # ### end Alembic commands ###
