"""fix_create_forma_de_pagamento

Revision ID: cd6219ac17a1
Revises: 0e2217bb1c56
Create Date: 2026-03-01 21:00:12.023333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6219ac17a1'
down_revision: Union[str, None] = '0e2217bb1c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formas_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DINHEIRO', 'CARTAO_DEBITO', 'CARTAO_CREDITO', 'PIX', name='tipopagamento'), nullable=False),
    sa.Column('valor_recebido', sa.Float(), nullable=False),
    sa.Column('troco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formas_pagamento_id'), 'formas_pagamento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formas_pagamento_id'), table_name='formas_pagamento')
    op.drop_table('formas_pagamento')
    # ### end Alembic commands ###
