"""add_relacionamento_user_e_vendas

Revision ID: d9ec20bcaf49
Revises: 5d107d98388c
Create Date: 2026-03-18 01:21:58.871465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ec20bcaf49'
down_revision: Union[str, None] = '5d107d98388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vendas', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'usuario_id')
    # ### end Alembic commands ###
