"""add_email_usuario

Revision ID: f3f8838fd166
Revises: 163ec5cefca9
Create Date: 2026-03-08 03:51:13.634435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f8838fd166'
down_revision: Union[str, None] = '163ec5cefca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
